### ISSUE TITLE
github.com/google/zopfli: loader fail

### ISSUE THREAD

**Issue by cznic** [cznic/99c#7]
With #6 fixed:

```
jnml@4670:~/src/github.com/google/zopfli/src/zopfli$ 99c *.c
99c: virtual.LoadMain: blocksplitter.c:244:25: TODO *func(uint64,*struct{})float64 -> func(uint64,*struct{})float64
goroutine 1 [running]:
runtime/debug.Stack(0xc420d86c80, 0x6767e0, 0xc4210efe30)
	/home/jnml/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cznic/virtual.LoadMain.func1(0xc420d89970)
	/home/jnml/src/github.com/cznic/virtual/loader.go:2599 +0x6e
panic(0x6767e0, 0xc4210efe30)
	/home/jnml/go/src/runtime/panic.go:491 +0x283
github.com/cznic/virtual.(*loader).loadFunctionDefinition(0xc420ada120, 0x85, 0xc420caba40)
	/home/jnml/src/github.com/cznic/virtual/loader.go:1294 +0x1932d
github.com/cznic/virtual.(*loader).load(0xc420ada120, 0xad, 0x100)
	/home/jnml/src/github.com/cznic/virtual/loader.go:2509 +0x15d1
github.com/cznic/virtual.LoadMain(0xc4215a0000, 0xad, 0x100, 0x0, 0x0, 0x0)
	/home/jnml/src/github.com/cznic/virtual/loader.go:2605 +0x80
main.(*task).main(0xc420d89e80, 0x0, 0x0)
	/home/jnml/src/github.com/cznic/99c/main.go:506 +0x19a7
main.main()
	/home/jnml/src/github.com/cznic/99c/main.go:52 +0x151

jnml@4670:~/src/github.com/google/zopfli/src/zopfli$
```

**Comment by cznic** [comment]
Fix for this seems trivial, blocked on reopened #6.

**Comment by cznic** [comment]
Closed by https://github.com/cznic/virtual/commit/cb9a59288892b507db039bd5374195305f7c9519.
