### ISSUE TITLE
libxcb-1.12: missing builtins

### ISSUE THREAD

**Issue by cznic** [cznic/99c#8]
```
jnml@4670:~/libxcb-1.12$ CC=99c ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for a Python interpreter with version >= 2.6... python
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... linux2
checking for python script directory... ${prefix}/lib/python2.7/dist-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/dist-packages
checking for style of include used by make... GNU
checking for gcc... 99c
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... no
checking whether 99c accepts -g... yes
checking for 99c option to accept ISO C89... none needed
checking whether 99c understands -c and -o together... no
checking dependency style of /home/jnml/libxcb-1.12/build-aux/compile 99c... none
checking how to run the C preprocessor... /lib/cpp
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... no
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... no
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for non-GNU ld... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from /home/jnml/libxcb-1.12/build-aux/compile 99c object... failed
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking for /home/jnml/libxcb-1.12/build-aux/compile 99c option to produce PIC...  -DPIC
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c PIC flag  -DPIC works... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c static flag  works... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -c -o file.o... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -c -o file.o... (cached) yes
checking whether the /home/jnml/libxcb-1.12/build-aux/compile 99c linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for /home/jnml/libxcb-1.12/build-aux/compile 99c option to accept ISO C99... unsupported
checking whether __clang__ is declared... no
checking whether __INTEL_COMPILER is declared... no
checking whether __SUNPRO_C is declared... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Werror=unknown-warning-option... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Werror=unused-command-line-argument... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Wall... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Wpointer-arith... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Wmissing-declarations... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Wformat=2... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Wstrict-prototypes... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Wmissing-prototypes... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Wnested-externs... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Wbad-function-cast... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Wold-style-definition... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Wdeclaration-after-statement... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Wunused... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Wuninitialized... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Wshadow... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Wmissing-noreturn... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Wmissing-format-attribute... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Wredundant-decls... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Wlogical-op... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Werror=implicit... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Werror=nonnull... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Werror=init-self... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Werror=main... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Werror=missing-braces... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Werror=sequence-point... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Werror=return-type... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Werror=trigraphs... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Werror=array-bounds... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Werror=write-strings... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Werror=address... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Werror=int-to-pointer-cast... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Werror=pointer-to-int-cast... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -pedantic... no
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Werror... yes
checking if /home/jnml/libxcb-1.12/build-aux/compile 99c supports -Werror=attributes... yes
Package xorg-macros was not found in the pkg-config search path.
Perhaps you should add the directory containing `xorg-macros.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xorg-macros' found
checking whether make supports nested variables... (cached) yes
checking whether to build developer documentation... yes
checking for doxygen... no
configure: WARNING: doxygen not found - documentation targets will be skipped
configure: WARNING: dot not found - doxygen targets will be skipped
checking for CHECK... no
checking for XCBPROTO... yes
checking for NEEDED... yes
checking for XDMCP... yes
checking for XdmcpWrap in -lXdmcp... no
checking XCBPROTO_XCBINCLUDEDIR... /usr/share/xcb
checking XCBPROTO_XCBPYTHONDIR... /usr/lib/python2.7/dist-packages
checking for ANSI C header files... (cached) no
checking for library containing getaddrinfo... no
checking for library containing connect... no
checking for library containing sendmsg... no
checking for struct msghdr.msg_control... yes
checking for struct sockaddr_un.sun_len... no
checking tsol/label.h usability... no
checking tsol/label.h presence... no
checking for tsol/label.h... no
checking for is_system_labeled... no
checking whether IOV_MAX is declared... no
checking whether UIO_MAXIOV is declared... yes
checking whether /home/jnml/libxcb-1.12/build-aux/compile 99c supports symbol visibility... no
checking for getaddrinfo... no
checking for poll... no
checking for launchd... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating man/Makefile
config.status: creating src/Makefile
config.status: creating tests/Makefile
config.status: creating xcb.pc
config.status: creating xcb-composite.pc
config.status: creating xcb-damage.pc
config.status: creating xcb-dpms.pc
config.status: creating xcb-dri2.pc
config.status: creating xcb-dri3.pc
config.status: creating xcb-glx.pc
config.status: creating xcb-present.pc
config.status: creating xcb-randr.pc
config.status: creating xcb-record.pc
config.status: creating xcb-render.pc
config.status: creating xcb-res.pc
config.status: creating xcb-screensaver.pc
config.status: creating xcb-shape.pc
config.status: creating xcb-shm.pc
config.status: creating xcb-sync.pc
config.status: creating xcb-xevie.pc
config.status: creating xcb-xf86dri.pc
config.status: creating xcb-xfixes.pc
config.status: creating xcb-xinerama.pc
config.status: creating xcb-xinput.pc
config.status: creating xcb-xkb.pc
config.status: creating xcb-xprint.pc
config.status: creating xcb-xselinux.pc
config.status: creating xcb-xtest.pc
config.status: creating xcb-xv.pc
config.status: creating xcb-xvmc.pc
config.status: creating doc/xcb.doxygen
config.status: creating src/config.h
config.status: executing depfiles commands
config.status: executing libtool commands

  Package: libxcb 1.12

  Configuration
    XDM support.........: no
    sendmsg fd passing..: no
    Build unit tests....: no
      with html results.: no
    XCB buffer size.....: 16384

  X11 extensions
    Composite...........: yes
    Damage..............: yes
    Dpms................: yes
    Dri2................: yes
    Dri3................: no
    Glx.................: yes
    Randr...............: yes
    Record..............: yes
    Render..............: yes
    Resource............: yes
    Screensaver.........: yes
    selinux.............: no
    Shape...............: yes
    Shm.................: yes
    Sync................: yes
    Xevie...............: no
    Xfixes..............: yes
    Xfree86-dri.........: yes
    xinerama............: yes
    xinput..............: no
    xkb.................: yes
    xprint..............: no
    xtest...............: yes
    xv..................: yes
    xvmc................: yes

  Used CFLAGS:
    CPPFLAGS............: 
    CFLAGS..............: -g

  Installation:
    Prefix..............: /usr/local

jnml@4670:~/libxcb-1.12$ CC=99c make
Making all in src
make[1]: Vstupuje se do adresáře „/home/jnml/libxcb-1.12/src“
  GEN      xproto.c
  GEN      bigreq.c
  GEN      xc_misc.c
  GEN      composite.c
  GEN      damage.c
  GEN      dpms.c
  GEN      dri2.c
  GEN      dri3.c
  GEN      present.c
  GEN      glx.c
  GEN      randr.c
  GEN      record.c
  GEN      render.c
  GEN      res.c
  GEN      screensaver.c
  GEN      shape.c
  GEN      shm.c
  GEN      sync.c
  GEN      xevie.c
  GEN      xf86dri.c
  GEN      xfixes.c
  GEN      xinerama.c
  GEN      xinput.c
  GEN      xkb.c
  GEN      xprint.c
  GEN      xselinux.c
  GEN      xtest.c
  GEN      xv.c
  GEN      xvmc.c
make  all-am
make[2]: Vstupuje se do adresáře „/home/jnml/libxcb-1.12/src“
  CC       xcb_conn.lo
  CC       xcb_out.lo
  CC       xcb_in.lo
  CC       xcb_ext.lo
  CC       xcb_xid.lo
  CC       xcb_list.lo
  CC       xcb_util.lo
  CC       xcb_auth.lo
  CC       xproto.lo
  CC       bigreq.lo
  CC       xc_misc.lo
  CCLD     libxcb.la
99c: xcb_conn.c:456:5: ir.linker undefined external global __FD_ZERO
Makefile:934: návod pro cíl „libxcb.la“ selhal
make[2]: *** [libxcb.la] Chyba 1
make[2]: Opouští se adresář „/home/jnml/libxcb-1.12/src“
Makefile:771: návod pro cíl „all“ selhal
make[1]: *** [all] Chyba 2
make[1]: Opouští se adresář „/home/jnml/libxcb-1.12/src“
Makefile:788: návod pro cíl „all-recursive“ selhal
make: *** [all-recursive] Chyba 1
jnml@4670:~/libxcb-1.12$ 
```

**Comment by cznic** [comment]
Progress hits another bug:

```
$ make
Making all in src
make[1]: Entering directory '/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/src'
  GEN      xproto.c
  GEN      bigreq.c
  GEN      xc_misc.c
  GEN      composite.c
  GEN      damage.c
  GEN      dpms.c
  GEN      dri2.c
  GEN      dri3.c
  GEN      present.c
  GEN      glx.c
  GEN      randr.c
  GEN      record.c
  GEN      render.c
  GEN      res.c
  GEN      screensaver.c
  GEN      shape.c
  GEN      shm.c
  GEN      sync.c
  GEN      xevie.c
  GEN      xf86dri.c
  GEN      xfixes.c
  GEN      xinerama.c
  GEN      xinput.c
  GEN      xkb.c
  GEN      xprint.c
  GEN      xselinux.c
  GEN      xtest.c
  GEN      xv.c
  GEN      xvmc.c
make  all-am
make[2]: Entering directory '/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/src'
  CC       xcb_conn.lo
  CC       xcb_out.lo
  CC       xcb_in.lo
  CC       xcb_ext.lo
  CC       xcb_xid.lo
  CC       xcb_list.lo
  CC       xcb_util.lo
  CC       xcb_auth.lo
  CC       xproto.lo
  CC       bigreq.lo
  CC       xc_misc.lo
  CCLD     libxcb.la
99c: virtual.LoadMain: "": unexpected "tokEOF" ("")
goroutine 1 [running]:
runtime/debug.Stack(0xc421138bf8, 0x677920, 0xc420c696c0)
	/home/jnml/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cznic/virtual.LoadMain.func1(0xc42113b970)
	/home/jnml/src/github.com/cznic/virtual/loader.go:2599 +0x6e
panic(0x677920, 0xc420c696c0)
	/home/jnml/go/src/runtime/panic.go:491 +0x283
github.com/cznic/ir.TypeCache.MustType(0xc420d4e3f0, 0x0, 0xc420d4e810, 0x0)
	/home/jnml/src/github.com/cznic/ir/type.go:607 +0x159
github.com/cznic/virtual.(*loader).loadFunctionDefinition(0xc420d7a000, 0x0, 0x815880)
	/home/jnml/src/github.com/cznic/virtual/loader.go:885 +0xa6
github.com/cznic/virtual.(*loader).load(0xc420d7a000, 0x49a, 0x500)
	/home/jnml/src/github.com/cznic/virtual/loader.go:2509 +0x15d1
github.com/cznic/virtual.LoadMain(0xc420c9e000, 0x49a, 0x500, 0x0, 0x0, 0x0)
	/home/jnml/src/github.com/cznic/virtual/loader.go:2605 +0x80
main.(*task).main(0xc42113be80, 0x0, 0x0)
	/home/jnml/src/github.com/cznic/99c/main.go:514 +0x19a7
main.main()
	/home/jnml/src/github.com/cznic/99c/main.go:52 +0x151

Makefile:934: recipe for target 'libxcb.la' failed
make[2]: *** [libxcb.la] Error 1
make[2]: Leaving directory '/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/src'
Makefile:771: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/src'
Makefile:788: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by cznic** [comment]
Progress:

```
$ make
Making all in src
make[1]: Entering directory '/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/src'
  GEN      xproto.c
  GEN      bigreq.c
  GEN      xc_misc.c
  GEN      composite.c
  GEN      damage.c
  GEN      dpms.c
  GEN      dri2.c
  GEN      dri3.c
  GEN      present.c
  GEN      glx.c
  GEN      randr.c
  GEN      record.c
  GEN      render.c
  GEN      res.c
  GEN      screensaver.c
  GEN      shape.c
  GEN      shm.c
  GEN      sync.c
  GEN      xevie.c
  GEN      xf86dri.c
  GEN      xfixes.c
  GEN      xinerama.c
  GEN      xinput.c
  GEN      xkb.c
  GEN      xprint.c
  GEN      xselinux.c
  GEN      xtest.c
  GEN      xv.c
  GEN      xvmc.c
make  all-am
make[2]: Entering directory '/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/src'
  CC       xcb_conn.lo
  CC       xcb_out.lo
  CC       xcb_in.lo
  CC       xcb_ext.lo
  CC       xcb_xid.lo
  CC       xcb_list.lo
  CC       xcb_util.lo
  CC       xcb_auth.lo
  CC       xproto.lo
  CC       bigreq.lo
  CC       xc_misc.lo
  CCLD     libxcb.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       composite.lo
  CCLD     libxcb-composite.la
99c: fatal error: unrecognized file type: ./.libs/libxcb.so
Makefile:856: recipe for target 'libxcb-composite.la' failed
make[2]: *** [libxcb-composite.la] Error 1
make[2]: Leaving directory '/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/src'
Makefile:771: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/src'
Makefile:788: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
jnml@r550:~/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12$ 
```

**Comment by cznic** [comment]
With https://github.com/cznic/99c/commit/e56e4569464ec97dcdf38341df53373234d1dcdf:

```
jnml@4670:~/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12$ make
Making all in src
make[1]: Vstupuje se do adresáře „/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/src“
  GEN      xproto.c
  GEN      bigreq.c
  GEN      xc_misc.c
  GEN      composite.c
  GEN      damage.c
  GEN      dpms.c
  GEN      dri2.c
  GEN      dri3.c
  GEN      present.c
  GEN      glx.c
  GEN      randr.c
  GEN      record.c
  GEN      render.c
  GEN      res.c
  GEN      screensaver.c
  GEN      shape.c
  GEN      shm.c
  GEN      sync.c
  GEN      xevie.c
  GEN      xf86dri.c
  GEN      xfixes.c
  GEN      xinerama.c
  GEN      xinput.c
  GEN      xkb.c
  GEN      xprint.c
  GEN      xselinux.c
  GEN      xtest.c
  GEN      xv.c
  GEN      xvmc.c
make  all-am
make[2]: Vstupuje se do adresáře „/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/src“
  CC       xcb_conn.lo
  CC       xcb_out.lo
  CC       xcb_in.lo
  CC       xcb_ext.lo
  CC       xcb_xid.lo
  CC       xcb_list.lo
  CC       xcb_util.lo
  CC       xcb_auth.lo
  CC       xproto.lo
  CC       bigreq.lo
  CC       xc_misc.lo
  CCLD     libxcb.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       composite.lo
  CCLD     libxcb-composite.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       damage.lo
  CCLD     libxcb-damage.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       dpms.lo
  CCLD     libxcb-dpms.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       dri2.lo
  CCLD     libxcb-dri2.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       present.lo
  CCLD     libxcb-present.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       glx.lo
  CCLD     libxcb-glx.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       randr.lo
  CCLD     libxcb-randr.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       record.lo
  CCLD     libxcb-record.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       render.lo
  CCLD     libxcb-render.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       res.lo
  CCLD     libxcb-res.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       screensaver.lo
  CCLD     libxcb-screensaver.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       shape.lo
  CCLD     libxcb-shape.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       shm.lo
  CCLD     libxcb-shm.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       sync.lo
  CCLD     libxcb-sync.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       xf86dri.lo
  CCLD     libxcb-xf86dri.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       xfixes.lo
  CCLD     libxcb-xfixes.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       xinerama.lo
  CCLD     libxcb-xinerama.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       xkb.lo
  CCLD     libxcb-xkb.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       xtest.lo
  CCLD     libxcb-xtest.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       xv.lo
  CCLD     libxcb-xv.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       xvmc.lo
  CCLD     libxcb-xvmc.la
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Opouští se adresář „/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/src“
make[1]: Opouští se adresář „/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/src“
Making all in tests
make[1]: Vstupuje se do adresáře „/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/tests“
make[2]: Vstupuje se do adresáře „/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/tests“
make[2]: Pro „all-am“ nebude nic uděláno.
make[2]: Opouští se adresář „/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/tests“
make[1]: Opouští se adresář „/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/tests“
Making all in doc
make[1]: Vstupuje se do adresáře „/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/doc“
make[1]: Pro „all“ nebude nic uděláno.
make[1]: Opouští se adresář „/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/doc“
Making all in man
make[1]: Vstupuje se do adresáře „/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/man“
  GEN      xcb-examples.3
  GEN      xcb-requests.3
make[1]: Opouští se adresář „/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12/man“
make[1]: Vstupuje se do adresáře „/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12“
make[1]: Pro „all-am“ nebude nic uděláno.
make[1]: Opouští se adresář „/home/jnml/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12“
jnml@4670:~/src/github.com/cznic/tmp/99c/xcb/libxcb-1.12$ 
```
